#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pyroute2
Version  : 0.7.3
Release  : 76
URL      : https://files.pythonhosted.org/packages/9c/e6/8d163b1aea84223696fef8f8c55566adf166b79d614d602469d64af00226/pyroute2-0.7.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/9c/e6/8d163b1aea84223696fef8f8c55566adf166b79d614d602469d64af00226/pyroute2-0.7.3.tar.gz
Summary  : Python Netlink library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-2.0+
Requires: pypi-pyroute2-bin = %{version}-%{release}
Requires: pypi-pyroute2-license = %{version}-%{release}
Requires: pypi-pyroute2-python = %{version}-%{release}
Requires: pypi-pyroute2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
Pyroute2
========
Pyroute2 is a pure Python **netlink** library. The core requires only Python
stdlib, no 3rd party libraries. The library was started as an RTNL protocol
implementation, so the name is **pyroute2**, but now it supports many netlink
protocols. Some supported netlink families and protocols:

%package bin
Summary: bin components for the pypi-pyroute2 package.
Group: Binaries
Requires: pypi-pyroute2-license = %{version}-%{release}

%description bin
bin components for the pypi-pyroute2 package.


%package license
Summary: license components for the pypi-pyroute2 package.
Group: Default

%description license
license components for the pypi-pyroute2 package.


%package python
Summary: python components for the pypi-pyroute2 package.
Group: Default
Requires: pypi-pyroute2-python3 = %{version}-%{release}

%description python
python components for the pypi-pyroute2 package.


%package python3
Summary: python3 components for the pypi-pyroute2 package.
Group: Default
Requires: python3-core
Provides: pypi(pyroute2)

%description python3
python3 components for the pypi-pyroute2 package.


%prep
%setup -q -n pyroute2-0.7.3
cd %{_builddir}/pyroute2-0.7.3
pushd ..
cp -a pyroute2-0.7.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662854435
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pyroute2
cp %{_builddir}/pyroute2-%{version}/LICENSE.Apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pyroute2/cd9bad64b174708395f795bb92f7b4be7d996e8f || :
cp %{_builddir}/pyroute2-%{version}/LICENSE.GPL-2.0-or-later %{buildroot}/usr/share/package-licenses/pypi-pyroute2/4cc77b90af91e615a64ae04893fdffa7939db84c || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/bin/ss2
rm -f %{buildroot}*/usr/bin/pyroute2-cli
## install_append content
rm -rf %{buildroot}/usr/lib/python3*/site-packages/tests
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyroute2-dhcp-client
/usr/bin/pyroute2-test-platform

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pyroute2/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/pypi-pyroute2/cd9bad64b174708395f795bb92f7b4be7d996e8f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
